const C = {
  GRID_W: 20,
  GRID_H: 20,
  MAX_PLAYERS: 4,
  START_HP: 100,
  TOTAL_POINTS: 12,
  MIN_PM: 2,
  MAX_PM: 6,
  DEFAULT_PA: 8,
  DEFAULT_PM: 4,
  TURN_TIME_MS: 120000,
  MAX_BOMBS_PER_PLAYER: 3,

  COST_PLACE_BOMB: 4,
  COST_DETONATE: 2,
  COST_REPULSEUR: 2,
  COST_SUBSTITUTION: 3,
  COST_RAPPEL: 1,
  COST_EXPULSION: 3,
  COST_AIMANT: 2,

  BOMB_PLACE_RANGE: 3,
  REPULSEUR_RANGE: 6,
  SUBSTITUTION_RANGE: 8,
  RAPPEL_RANGE: 6,
  AIMANT_RANGE: 6,
  DETONATE_RANGE: 10,

  CD_REPULSEUR: 1,
  CD_SUBSTITUTION: 5,
  CD_RAPPEL: 3,
  CD_EXPULSION: 10,

  EXPLOSION_RANGE: 2,
  WALL_MAX_GAP: 6,

  DMG_EXPLOSION: 20,
  DMG_WALL_2: 15,
  DMG_WALL_3PLUS: 25,

  AGE_BONUS_PER_TURN: 0.2,
  AGE_MAX: 4,

  BONUS_SPAWN_CHANCE: 0.33,
  BONUS_TYPES: ['bomb-bonus', 'range-bonus', 'explosion-bonus', 'move-bonus', 'action-bonus'],

  STALL_TURNS: 3,
  STALL_DAMAGE: 10,

  ZONE_START_CYCLE: 20, // Zone appears after this many complete cycles (all players having played)
  ZONE_DAMAGE: 10,

  REPULSEUR_PUSH: { 1: 3, 2: 2, 3: 1 },
  EXPULSION_PUSH: 5,
  AIMANT_PULL: 3,
};

module.exports = C;
